language: php

php:
  - "5.4"
  - "5.3"

env:
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

notifications:
  irc: "irc.freenode.net#orchestra-platform"

before_install:
  - cd ../../
  - git clone git://github.com/laravel/laravel.git
  - mv ./orchestral/orchestra ./laravel/bundles/orchestra
  - echo "<?php return array('orchestra' => array('auto' => true, 'handles' => 'orchestra'));" > ./laravel/application/bundles.php
  - cd ./laravel
  - php artisan bundle:install hybrid
  - php artisan bundle:install Messages
  - sh -c "if [ '$DB' = 'pdo/pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS orchestra;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pdo/pgsql' ]; then psql -c 'CREATE DATABASE orchestra;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pdo/mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS orchestra;'; fi"

script: "phpunit --coverage-text --configuration bundles/orchestra/tests/travis/$DB.phpunit.xml"
